### ISSUE TITLE
Indexers permanent time-out without Sonarr restart

### ISSUE THREAD

**Issue by ChromoX** [linuxserver/docker-sonarr#84] opened 2018-12-10 18:02 UTC
I am experiencing the following issue: https://github.com/Sonarr/Sonarr/issues/2802

It seems the only supported way to handle this situation is to downgrade Mono from 5.16 to 5.14.

Is this something you guys would be willing to do, or do I need to make my own custom images?

I'm running the latest version of the linuxserver/sonarr image on Docker 18.09.

Issue #83 also would be fixed with a downgrade of Mono from 5.16 to 5.14.

It seems that Mono 5.16 has many issues with Sonarr.

**Comment by rourke** [comment] 2019-01-03 10:13
This is getting quite annoying. Having to restart Sonarr every few days and linuxserver is not responding at all. If anyone figures out how to downgrade Mono, please share it.

**Comment by rourke** [comment] 2019-01-03 10:20
Calling the top contributors @sparklyballs and @lonix. According to the issue Mono 5.12 shouldn't have any problems: https://github.com/Sonarr/Sonarr/issues/2802

[This SO answer](https://stackoverflow.com/questions/33763177/install-older-version-of-mono) provides a way to stick to a specific Mono version, but I would have no idea how to do this inside a container.

**Comment by j0nnymoe** [comment] 2019-01-03 11:42
Are you running the latest version of our image? 

We would have to look at adjusting the baseimage this container uses to sick at a mono version and considering its used by multiple containers of ours, it's not something we can just apply without considering the other containers. 

It's strange that this issue only seems to be causing problems for a handful of users.

**Comment by rourke** [comment] 2019-01-03 11:56
I did a pull about 2 weeks ago, but I just did one again, so now I do. It seems to only update Mono to 5.18.0.225. Which is confirmed to not solve the problem. Unfortunately I'm not experienced enough to figure out the common factor. I got a hunch it's only causing problems on Ubuntu.

**Comment by j0nnymoe** [comment] 2019-01-03 12:02
Curious to know, how did you install docker on Ubuntu?

**Comment by rourke** [comment] 2019-01-03 12:06
Through the [official installation instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/). I'm also using docker-compose which I also installed [the same way](https://docs.docker.com/compose/install/).

**Comment by JAGFin1** [comment] 2019-01-03 12:13
It will be interesting to compare my Docker engine version against yours. I am running Ubuntu 16.04 LTS (I don’t have the engine version to hand). Something may have changed in more recent versions of Docker or Ubuntu itself which is causing this, as I currently do not have this problem and am running the latest build of our image.

**Comment by rourke** [comment] 2019-01-03 12:42
I'm running Ubuntu Server 16.04 LTS and this is its engine information:

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:01 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:31 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by ChromoX** [comment] 2019-01-04 04:50
I'm running Debian Stretch as well. I have the indexer problem, and memory "sucking" as well.

Running the latest linuxserver/sonarr image.

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:46 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

My current fix has been to have a cronjob restart the Sonarr process once a day.

**Comment by JDtheHutt** [comment] 2019-01-13 20:20
I have the same issue running on Arch.  Sonarr starts off running fine and goes for a few weeks, then it just starts spewing errors on startup and the WebGUI becomes very sluggish/impossible to load, which i assume is due to the massive number of errors occurring.  The errors all relate to DNS resolution and also that it is unable to connect to indexers (through Jackett in another container or external NZB APIs) and also cannot connect to local download clients (sabnzbd and transmission also running in the same docker host).

Radarr works perfectly, I don't get these issues with it at all.  Nor with Lidarr.  I have found that even rolling my container back to images from weeks or months ago that used to work doesn't fix this.  Once it has happened, it seems to break the settings in my persistent data volume itself.  Backing up settings and restoring under a clean container/volume setup breaks it again.  I have to completely purge everything and manually setup Sonarr all over again, which is becoming a bit of a nightmare.

**Comment by rafal-krypa** [comment] 2019-01-17 13:49
Having the same issue since at least two months, I recently tested going back to latest version no affected by the bug. It seems that `linuxserver/sonarr:158` is the latest image based on Mono 5.14. I have it working perfectly for three days already. Until this issue is fixed, it seems like a viable workaround.

**Comment by jbishop129** [comment] 2019-01-26 15:14
Same issue here with Sonarr after a few days. I’m running as a docker service, with persistent mount across my swarm hosts via NFS, for what it’s worth. Every few days all indexers would be “failed”, and a relaunch of the container would fix it. Rolled back to :158 with mono 5:14 and it’s been stable about a week

**Comment by RoccoMathijn** [comment] 2019-01-27 18:33
Same issue here. Ran on 158 successfully for a week but just switched to https://hub.docker.com/r/gh0str1pp3r/sonarr

**Comment by rourke** [comment] 2019-01-28 23:06
> Same issue here. Ran on 158 successfully for a week but just switched to https://hub.docker.com/r/gh0str1pp3r/sonarr

I'm running this too for a while now, and it completely fixed it. Falling back to Mono 5.12 is the solution.

**Comment by Xaelias** [comment] 2019-02-09 23:44
Yeah experiencing this while running the container inside k8s. This is really annoying. Basically have to check on sonarr daily to make sure it's not timing out. Which... kind of defeats the purpose of having an automated solution :-(
If you guys could consider updating mono in your image, that would be awesome.
In the meantime, I guess I'll try version 158.

**Comment by thelamer** [comment] 2019-02-15 05:30
Can anyone in this thread test out lspipepr/sonarr:2.0.0.5301-pkg-f35751c9-pr-99 ?
It is a version that is using mono 5.14 stable.

**Comment by manubell** [comment] 2019-03-04 22:03
@thelamer 5 days in so far and no issues with that container. 
Before I was having issues after 2-3 days already so seems good.

**Comment by Buri** [comment] 2019-03-25 19:27
Well, I had also this issue using docker image and in my case problem was docker was trying to use IPv6 for some reason. I disabled it with
```
sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
```
and its working now. This is with mono 5.18 and preview version.

Hope that helps

**Comment by ChromoX** [comment] 2019-04-08 03:27
I tried @Buri's idea above. It didn't end up working for me for tag `latest`.

**Comment by apat183** [comment] 2019-05-09 07:49
Is there any workarounds for this, just did a fresh install and whenever I log into Sonarr it says indexes are down.

**Comment by thelamer** [comment] 2019-05-10 22:38
@manubell  Our initial route of testing was to lock mono into version 5.14, there was some reported success including you.
But we need to rebase these images to Bionic which resets the testing cycle. We stuck with head mono on this one. 

I hate to put this on you, but it is a tough problem to replicate locally can you try out this image which is the current stable release in a bionic based container and mono 5.18? 
```
lspipepr/sonarr:2.0.0.5321-pkg-e56de2cc-pr-108
```

**Comment by Repooc** [comment] 2019-05-11 17:59
> @manubell Our initial route of testing was to lock mono into version 5.14, there was some reported success including you.
> But we need to rebase these images to Bionic which resets the testing cycle. We stuck with head mono on this one.
> 
> I hate to put this on you, but it is a tough problem to replicate locally can you try out this image which is the current stable release in a bionic based container and mono 5.18?
> 
> ```
> lspipepr/sonarr:2.0.0.5321-pkg-e56de2cc-pr-108
> ```

Now need a version of Sonarr v3 with a mono version that doesn't break talking to indexers as the test versions you asked people to try seem to be on Sonarr v2

**Comment by thelamer** [comment] 2019-05-11 18:02
We have that too :
lspipepr/sonarr:3.0.1.490-pkg-e56de2cc-pr-109
This is the bionic version of the preview branch.

**Comment by Repooc** [comment] 2019-05-11 18:04
Is that with mono 5.14 or 5.18... I keep seeing people have better luck with 5.14... I can install 5.18 to see if I have any issues with it even if its on 5.18.  Also, I assume I can use the same unraid template but instead of using the repo linuxserver/sonarr:preview i just used the one you just suggested?

**Comment by thelamer** [comment] 2019-05-11 18:07
Latest mono, as I have said we are moving to bionic regardless and we are resetting the testing loop at the current version of mono.

**Comment by Repooc** [comment] 2019-05-11 18:09
Can I asked what is the difference between the one I am using and the one you just linked me?

**Comment by thelamer** [comment] 2019-05-11 18:20
Bionic is on 5.20.1.19 so same goes for all versions of sonarr.

**Comment by Repooc** [comment] 2019-05-11 18:49
So i guess there is no difference between the 2 then?

**Comment by jbishop129** [comment] 2019-05-13 14:28
> We have that too :
> lspipepr/sonarr:3.0.1.490-pkg-e56de2cc-pr-109
> This is the bionic version of the preview branch.

FWIW I just updated my stack to use this Sonarr v3.0 container; I was previously holding back at `linuxserver/sonarr:158` for stability.
`Version
3.0.1.490`
`Package Version
3.0.1.490-pkg-e56de2cc-pr-109 by linuxserver.io`
`Mono Version
5.20.1.19`

I'll report back in a few days on stability of this branch, specifically about Jackett indexers remaining healthy or not.

**Comment by jbishop129** [comment] 2019-05-14 16:39
Unfortunately I'm experiencing the same failed indexers behavior after some time, when running on the  `lspipepr/sonarr:3.0.1.490-pkg-e56de2cc-pr-109` image as well. As was true before, after a day or so, the indexers all report failed, and clicking on Test ultimately times out. I confirmed the actual indexer in Jackett is in fact responding normally both in Jackett's UI, and curling it via API. 

I notice in the container logs, the failed API call is reported. I copied that URL, console'ed in to the sonarr container, and `curl`ed the same API endpoint, and it responds. This is odd behavior. 

Happy to help troubleshoot this, just give me instructions!

**Comment by thelamer** [comment] 2019-05-19 18:34
To everyone in this thread if you are having perm timeout issues please use this new tag: 
```
linuxserver/sonarr:5.14
```
It uses an older version of Mono that some users have reported does not have the same issues as the current 5.20 version. 

This tag will always be the current stable version of Sonarr, we will not be creating 5.14 versions for pre-releases or development versions of Sonarr. 
If this version of mono does not alleviate the timeout issues for you , then report these bugs upstream to Sonarr and Jackett.

I am closing this issue, I hope everyone in this thread understands that we can only do so much for the application only controlling the Docker environment it is running in.

**Closed by thelamer** 2019-05-19 18:34 UTC

**Comment by Repooc** [comment] 2019-05-19 22:42
So this is for Sonarr v2? If so that is not ideal for a good chunk of us 😪 Appreciate the work though for sure.
