### ISSUE TITLE
[BUG] Optional volumes mounted with incorrect permissions when running in rootless Docker

### ISSUE THREAD

**Issue by Razerfish** [linuxserver/docker-sonarr#299] opened 2024-08-10 21:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Optional volumes such as `/tv` and `/downloads` are mounted as being owned by `root` rather than by user `abc` when running in rootless Docker.

### Expected Behavior

The aforementioned volumes should be mounted with user `abc` as the owner as they are when running with non-rootless Docker.

### Steps To Reproduce

1. In Ubuntu 24.04 with Docker installed from `get-docker.sh` from `https://get.docker.com` and Docker rootless installed via `dockerd-rootless-setuptool.sh`.
2. With this file structure:
```
/home/fiona/
├── downloads
├── sonarr
└── tv
```
3. Use the example compose file with paths updated to reflect the existing file structure.
4. Attempt to configure a root directory under Settings>Media Management.

### Environment

```markdown
- OS: Ubuntu 24.04
- How docker service was installed: `get-docker.sh` and `dockerd-rootless-setuptool.sh`
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/fiona/sonarr/config:/config
      - /home/fiona/tv:/tv
      - /home/fiona/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 4.0.8.1874-ls250
Build-date: 2024-08-09T23:32:52+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
[Debug] Bootstrap: Console selected 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Trace] EventAggregator: Publishing ConfigFileSavedEvent 
[Debug] MigrationController: Took: 00:00:04.2079016 
[Trace] EventAggregator: ConfigFileSavedEvent ~> ReconfigureLogging 
[ls.io-init] done.
[Warn] SonarrErrorPipeline: Invalid request Validation failed: 
 -- Path: Folder '/tv/' is not writable by user 'abc'
```

**Comment by aptalca** [comment] 2024-08-10 21:37
Optional volumes are entirely managed by the user. The container does not touch their permissions and expects them to be correct. 

Also, we don't provide official support for rootless docker, but we can provide some help in discord 
https://docs.linuxserver.io/misc/support-policy/#reasonable-endeavours-support

Closing as it's not a bug

**Closed by aptalca** 2024-08-10 21:37 UTC

**Comment by klinki** [comment] 2024-12-20 22:50
@Razerfish did you manage to get it running? I'm facing exactly the same issue.

**Comment by thespad** [comment] 2024-12-20 22:58
This is a misunderstanding of how rootless docker operates. It performs users remapping; the permissions haven't changed, your view of them has.

"root" (i.e. uid 0) in a rootless container is the user who created it (often 1000, can be anything). Other host users will be remapped to dedicated uid range.

**Comment by Razerfish** [comment] 2024-12-20 23:17
@klinki No, sorry. I just ended up switching back to standard docker.
