### ISSUE TITLE
Why run sonarr with --debug flag ?

### ISSUE THREAD

**Issue by ddonindia** [linuxserver/docker-sonarr#167] opened 2020-09-24 09:49 UTC
Just wondering why docker container runs Sonarr.exe with mono `--debug` flag? 
Can we remove it ?

**Comment by hotio** [comment] 2020-10-14 12:43
It's so that the Sonarr devs have some useful info in the logs, so no it can't be removed unless we would want to annoy them....

**Comment by Ornias1993** [comment] 2020-11-04 22:29
Can there at least be an (env var?) option to override it on purpose?

**Comment by hotio** [comment] 2020-11-05 09:21
What would be the point?

**Comment by Ornias1993** [comment] 2020-11-05 12:14
Debug modes always have an overhead. It's not 100% free.

**Comment by aptalca** [comment] 2020-11-05 13:07
Feel free to use a custom script to modify it for yourself: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

We're not planning to change that behavior in the image.

**Comment by Ornias1993** [comment] 2020-11-05 13:18
Nice article, but it doesn't really apply here imho. I understand we shouldn't expect all sorts of defaults being overrideable.

But in this case, you guys deviate from the original intended behavior of mono, so us users need to use customisations to revert it? All we ask for is the option to run mono as intended by... Mono devs, integrated in the image. Because you SHOULD be able to without customisation.

I'm not asking for a "swiss army knive", i'm asking you guys not to needlessly deviate from default behavior or atleast give the option to disable said deviation.

**Comment by aptalca** [comment] 2020-11-05 13:23
Well, we'll have to agree to disagree then.

The linked article explains how you can easily modify any default behavior via custom scripts while making your changes persistent.

Closing this as it is not a bug.

**Closed by aptalca** 2020-11-05 13:23 UTC

**Comment by Ornias1993** [comment] 2020-11-05 13:25
I agree to disagree it's a bug...
A layer 8 one in the developers circle imho.

**Comment by hotio** [comment] 2020-11-05 13:35
Nice of you to claim that the mono devs intended to run without `--debug`, but where is your proof?

The Sonarr devs rather have you run with `--debug`. See https://github.com/Sonarr/Sonarr/wiki/Installation#linux

**Comment by Ornias1993** [comment] 2020-11-05 13:44
> Nice of you to claim that the mono devs intended to run without `--debug`, but where is your proof?

It not being the default?

**Comment by hotio** [comment] 2020-11-05 13:49
you claim `All we ask for is the option to run mono as intended by... Mono devs`

where do they state that? they provide the `--debug` argument afterall....and the sonarr devs want the extra info it provides....

You rather have a programm full of bugs and memory leaks instead of running with `--debug`? It's already hard enough to get people to provide a proper log file, wouldn't even wanna imagine how to explain to them that they now need to run with `--debug` enabled and recreate the bug....

But, sounds that you are techinical enough to just fork the image, remove the flag and run you own image.....

**Comment by Ornias1993** [comment] 2020-11-05 13:55
> But, sounds that you are techinical enough to just fork the image, remove the flag and run you own image.....

Indeed I am... and maybe I should..
Some more things that are inherently not how I like it... Like using chmod after init, which makes it impossible to run readonly_root (even though s6 supports it (somewhat)) and lack of integrated healthchecks in accordance with CIS guidelines.

Totally offtopic, got any links you use to sync hotio with linuxserver upstreams by any chance, or is it mostly manual labor?

**Comment by hotio** [comment] 2020-11-05 13:56
?? sync what?

**Comment by Ornias1993** [comment] 2020-11-05 14:23
> ?? sync what?

Whoops that scentence got messed up...
Got any link **to tools** to sync your own container repo's based on Linuxserver (some of yours are), with the upstream linux server repo?

**Comment by hotio** [comment] 2020-11-05 14:50
none of mine are based on linuxserver containers

**Comment by Ornias1993** [comment] 2020-11-05 15:37
@hotio Whoops I also see now, I must've been mistaken by the list of linuxio forks... Sorry!
Your containers look great btw, might move over myself, thanks anyway! :)
